apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hubot
  name: hubot
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hubot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: hubot
    spec:
      containers:
      - name: hubot
        imagePullPolicy: Always
        image: quay.io/rk295/kubernetes-hubot:latest
        env:
        - name: DEBUG
          value: "true"
        - name: HUBOT_SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              key: HUBOT_SLACK_TOKEN
              name: hubot
        - name: MAX_SEARCH_RESULTS
          value: "1"
        volumeMounts:
          - name: config
            mountPath: /hubot-scripts
      volumes:
        - name: config
          configMap:
            name: hubot
